version: "2"

services:
  juice-shop:
    container_name: juice-shop
    build:
      context: ./
    tty: true
    environment:
      NODE_ENV: ${NODE_ENV}
      CTF_KEY: ${CTF_KEY}
    ports:      
      - "${JUICE_SHOP_PORT}:3000"